node {

    stage('Clone repository') {
        
       checkout scm
dir("configserver") {

        withMaven(options:[artifactsPublisher(disabled: true)],globalMavenSettingsConfig: 'a288a6e3-2534-4b38-b639-829d0d7c459b', maven: 'maven', mavenOpts: '-DskipTests=true') {
  sh "mvn clean verify"}
}
    }
    
    pom = readMavenPom file: 'pom.xml'
    VERSION= pom.version
    fileName = "macellanconfig:${VERSION}"
    
    

    dockerfile = "/opt/docker/compose/docker-compose.yml"


    
      stage('Build & register') {
dir("configserver") {
          docker.withRegistry('https://dockerhub.ngss.io') {
              def customImage = docker.build("${fileName}")
              customImage.push()
          }
          }
      }
    

     }
